version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: nora-ai-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nora-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nora-ai-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/nora-ai
      - JWT_SECRET=your_jwt_secret_key
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=claude-3-sonnet-20240229
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - nora-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nora-ai-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - nora-network

networks:
  nora-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local